---
- name: bootstrap Arch Linux BTW system
  hosts: localhost

  vars_prompt:
    - name: user_password
      prompt: "user password:"
      encrypt: "sha512_crypt"
      private: yes
      confirm: yes

  pre_tasks:
    # Make prompted vars available for all plays.
    - set_fact:
      user_password: "{{ user_password }}"

  tasks:
    - import_role:
      name: archinstall
