---
- hosts: localhost
  name: bootstrap Arch Linux BTW system

  vars_prompt:
    - name: user_password
      prompt: "user password:"
      encrypt: "sha512_crypt"
      private: yes
      confirm: yes

  roles:
    - archinstall
