---
- hosts: localhost
  name: bootstrap Arch Linux BTW system

  vars_prompt:
    - name: user_password
      prompt: "user password:"
      encrypt: "sha512_crypt"
      private: yes
      confirm: yes

  tasks:
    - name: Abort if the host is not booted from the Arch install media
      fail:
        msg: "This host is not booted from the Arch install media!"
        when: ansible_nodename != 'archiso'

    - name: Synchronize clock via NTP
      command: timedatectl set-ntp true

  roles:
    - archinstall
