- hosts: localhost
  name: bootstrap Arch Linux BTW system
  connection: local

- tasks:
    - name: List devices
      command: lsblk -l

- vars_prompt:
    - name: user_password
      prompt: "user password:"
      encrypt: "sha512_crypt"
      private: yes
      confirm: yes


  roles:
    - archinstall
