---
- hosts: localhost
  name: bootstrap Arch Linux BTW system



- pre_tasks:
  # Make prompted vars available for all plays.
  #  - set_fact:
  #  user_password: "{{ user_password }}"
    
  - name: List devices
    command: lsblk -l

- vars_prompt:
    - name: user_password
      prompt: "user password:"
      encrypt: "sha512_crypt"
      private: yes
      confirm: yes

- tasks:
  - import_roles:
    name: archinstall
