---
- name: install required packages
  pacman:
    name:
      - xorg-server
      - xorg-xinit
      - libxinerama
      - fontconfig
      - libxrender
      - xorg-util-macros
      - xdg-utils
      - gnu-free-fonts
      - dunst
    state: present
  become: yes

    #- name: remove libxft as it conflicts with fix below
    #  pacman:
    #    name:
    #      - libxft
    #    state: absent
    #  become: yes

- name: Install libxft-bgra-git emoji fix
  shell: yay -S libxft-git --save --answerclean All --answerdiff None
  #shell: yay -S libxft-bgra-git --save --answerclean All --answerdiff None
  become: yes
  become_user: "{{ user.name }}"
