---
- name: install required packages
  pacman:
    name:
      - xorg-server
      - xorg-xinit
      - libxinerama
      - libxft
    state: present
  become: yes

- name: remove libxft as it conflicts with fix below
  pacman:
    name:
      - libxft
    state: absent
  become: yes

- name: Install libxft-bgra-git emoji fix
  shell: yay -S libxft-bgra-git --save --answerclean All --answerdiff None --useask
  become: yes
  become_user: "{{ user.name }}"
