---
# Rank Arch mirrors
- name: Install the pacman-contrib package (for rankmirrors)
  pacman:
    name:
      - pacman-contrib
    update_cache: yes

- name: Use rankmirrors to filter the fastest mirrors that support HTTPS
  shell: curl -s "https://www.archlinux.org/mirrorlist/?country=US&protocol=https&use_mirror_status=on" | sed -e 's/^#Server/Server/' -e '/^#/d' | rankmirrors -n 20 - > /etc/pacman.d/mirrorlist
#
