- name: partition drive
    parted:
      label: "{{ drive.table }}"
      device: "{{ drive.device }}"
      # Parted indexes partitions starting from 1:
      number: "{{ item.0 + 1 }}"
      name: "{{ item.1.name }}"
      part_start: "{{ item.1.start }}"
      part_end: "{{ item.1.end }}"
      part_type: "{{ item.1.type|default(omit) }}"
      flags: "{{ item.1.flags|default(omit) }}"
      state: present
    with_indexed_items:
      - "{{ drive.partitions }}"
