---
- name: install required packages
  pacman:
    name:
      - stow
    state: present
  become: yes

- name: Clone .dotfiles
  git:
    repo: https://github.com/jbestrom/.dotfiles.git
    dest: "${HOME}/.dotfiles"
    accept_hostkey: yes
    update: yes
  become: true
  become_user: "{{ user.name }}"

- name: Install dotfiles
  command: stow --overwrite
  args:
    chdir: "${HOME}/.dotfiles"
  become: yes
  become_user: "{{ user.name }}"
