---
- name: Clone DWM
  git:
    repo: https://github.com/jbestrom/dwm.git
    dest: "/home/{{ user.name }}/.local/src"
    accept_hostkey: yes
    update: yes
  become: true
  become_user: "{{ user.name }}"
