---
- name: Updating cache
  become: true
  pacman:
    update_cache: true

- name: Installing dependencies
  become: true
  pacman:
    name: base-devel

- name: Setting aur_user globally
  set_fact:
    aur_user: aur_builder

- name: Creating aur_builder
  become: true
  user:
    name: "{{ user.name }}"
    group: wheel

- name: Giving passwordless access to pacman
  become: true
  lineinfile:
    path: /etc/sudoers.d/11-install-{{ aur_user }}
    line: '{{ user.name }} ALL=(ALL) NOPASSWD: /usr/bin/pacman'
    create: true
    validate: 'visudo -cf %s'

- name: Installing yay
  become: true
  become_user: "{{ user.name }}"
  aur:
    name: yay
    use: makepkg
    skip_installed: true
