---
- name: configure repository mirrors
  command: "reflector --sort score -p https --country '{{ country }}' --save /etc/pacman.d/mirrorlist"

- name: install AUR package helper yay
  aur:
    name: yay
    user: "{{ user.name }}"
    dir: /tmp

