---
- name: Clone yay repo
  git: repo=https://aur.archlinux.org/yay.git dest=/tmp/yay/ accept_hostkey=yes update=yes
  become_user: "{{ user.name }}"

- name: Create yay package
  shell: cd /tmp/yay && makepkg -si --noconfirm
  become_user: "{{ user.name }}"
