---
- name: Set user.email
  community.general.git_config:
    name: user.email
    scope: global
    value: "{{ git_config_email }}"
      #    no_log: true

- name: Set user.name
  community.general.git_config:
    name: user.name
    scope: global
    value: "{{ git_config_name }}"
