---
- name: enable systemd-network service
  systemd:
    name: systemd-networkd
    enabled: yes

- name: configure br0.network
  template:
    src: br0.network.j2
    dest: /etc/systemd-network/br0.network
    mode: 440

- name: configure br0.netdev
  template:
    src: br0.netdev.j2
    dest: /etc/systemd-network/br0.netdev
    mode: 440

- name: Create network
  lineinfile:
    path: "/etc/systemd-network/10-{{ eth_device }}.network"
    state: present
    line: "{{ item }}"
  with_items:
    - "[Match]"
    - "Name={{ eth_device }}"
    - ""  
    - "[Network]"
    - "DHCP=ipv4"
    - "Bridge=br0"
