---
- name: rebuild initramfs
  command: mkinitcpio -p linux
  become: yes

- name: install bootloader packages
  pacman:
    name:
      - efibootmgr
  become: yes

- name: Install systemd-boot to /boot
  command: bootctl install
  become: yes

- name: Create loader config
  lineinfile:
    path: /boot/loader/loader.conf
    state: present
    line: "{{ item }}"
  with_items:
    - "default arch.conf"
    - "timeout 0"
  become: yes

- name: Generate PARTUUID
  command: "blkid -t PARTLABEL=root -l -s PARTUUID -o value"
  register: partuuid

- name: Create loader entry (AMD)
  lineinfile:
    path: /boot/loader/entries/arch.conf
    state: present
    create: yes
    line: "{{ item }}"
  with_items:
    - "title Arch Linux"
    - "linux /vmlinuz-linux"
    - "initrd /amd-ucode.img"
    - "initrd /initramfs-linux.img"
    - "options root=PARTUUID={{ partuuid.stdout }} rw {{ extra_kernel_params }}"
  when: ansible_processor[1].find('AMD') != -1
  become: yes

- name: Create loader entry (Intel)
  lineinfile:
    path: /boot/loader/entries/arch.conf
    state: present
    create: yes
    line: "{{ item }}"
  with_items:
    - "title Arch Linux"
    - "linux /vmlinuz-linux"
    - "initrd /intel-ucode.img"
    - "initrd /initramfs-linux.img"
    - "options root=PARTUUID={{ partuuid.stdout }} rw {{ extra_kernel_parms }}"
  when: ansible_processor[1].find('Intel') != -1
  become: yes
