---
install_drive: /dev/vda
username: josh
hostname: arch-beast
extra_kernel_params: ''
eth_device: enp1s0 
extra_roles: 
  - aur
  - dwm
  - dmenu
  - dwmblocks
  - st
  - dotfiles
  - qemu
  - systemd-network-with-bridge
