---
#- name: Mount efivars read-only to avoid EFIgeddon
#  mount: src=efivarfs path=/sys/firmware/efi/efivars fstype=efivarfs opts="ro,nosuid,nodev,noexec,noatime" state=present

- name: rebuild initramfs
  command: mkinitcpio -p linux

- name: 'detect boot firmware (UEFI or BIOS)'
  shell: '[ -d /sys/firmware/efi ] && echo UEFI || echo BIOS'
  register: firmware

    #- name: create /boot/EFI directory
    #file:
    #path: /boot/EFI
    #state: directory
    #when: firmware.stdout == 'UEFI'


- name: install bootloader packages
  pacman:
    name:
      - efibootmgr


- name: Install systemd-boot to /boot
  command: bootctl install


