---
- name: rebuild initramfs
  command: mkinitcpio -p linux

- name: install bootloader packages
  pacman:
    name:
      - efibootmgr


- name: Install systemd-boot to /boot
  command: bootctl install

- name: Create loader config
  blockinfile:
    path: /boot/loader/loader.conf
    block: "default arch.conf
      timeout 0"

