---
- name: rebuild initramfs
  command: mkinitcpio -p linux

- name: install bootloader packages
  pacman:
    name:
      - efibootmgr

- name: Install systemd-boot to /boot
  command: bootctl install

- name: Create loader config
  lineinfile:
    path: /boot/loader/loader.conf
    state: present
    line: "{{ item }}"
  with_items:
    - "default arch.conf"
    - "timeout 0"
