---
- name: rebuild initramfs
  command: mkinitcpio -p linux

- name: 'detect boot firmware (UEFI or BIOS)'
  shell: '[ -d /sys/firmware/efi ] && echo UEFI || echo BIOS'
  register: firmware

- name: create /boot/efi directory
  file:
    path: /boot/efi
    state: directory
    when: firmware.stdout == 'UEFI'


- name: install bootloader packages
  pacman:
    name:
      - systemd-boot
      - efibootmgr


- name: Install systemd-boot to /boot
  command: bootctl install


