---
- name: Set local timezone
  file:
    src: "/usr/share/zoneinfo/{{ timezone }}"
    dest: /etc/localtime
    state: link

- name: Generate adjtime file
  command: hwclock --systohc

- name: Configure locale.gen
  replace:
    dest: /mnt/etc/locale.gen
    regexp: '{{ item.regex }}'
    line: '{{ item.line }}'
  loop:
    - {regex: en_US\.UTF-8 UTF-8, line: en_US.UTF-8 UTF-8}

- name: Create locale.conf
  copy:
    content: "LANG=en_US.UTF-8"
    dest: /mnt/etc/locale.conf
            
- name: Generate locales
  command: locale-gen
