---
- name: Set local timezone
  file:
    src: "/usr/share/zoneinfo/{{ timezone }}"
    dest: /etc/localtime
    state: link

- name: Generate adjtime file
  command: hwclock --systohc

- name: Configure locale.gen
  replace:
      dest: /etc/locale.gen
      regexp: "#.*({{ item }}.UTF-8 UTF-8)"
      replace: '\1'
  with_items: "{{ locales }}"

- name: Create locale.conf
  copy:
    content: "LANG=en_US.UTF-8"
    dest: /mnt/etc/locale.conf
            
- name: Generate locales
  command: locale-gen
